CREATE TABLE IF NOT EXISTS player (
    id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    team_id VARCHAR(255) NOT NULL,
    PRIMARY KEY(id),
    FOREIGN KEY(team_id) REFERENCES team(id)
);